name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    name: Greet new participant
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '##Welcome!\n\nThank you for finding time to write an issue and make this extension better.\n\nI`ll get back to your ASAP.'
        pr-message: '##Welcome!\n\nThank you very match for your contribution. I very appriciate it.\n\nI`ll get to this PR ASAP.'
